CREATE TABLE IF NOT EXISTS wallet
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    publicToken VARCHAR(255) UNIQUE NOT NULL,
    secretToken VARCHAR(255) UNIQUE NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE INDEX IF NOT EXISTS IDX_PUB_SEC_TOKEN on wallet(publicToken,secretToken);