CREATE TABLE IF NOT EXISTS wallet
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    publicToken VARCHAR(255) UNIQUE NOT NULL,
    privateToken VARCHAR(255) UNIQUE NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_SECRET_TOKEN on wallet(publicToken,privateToken);